name: "Semantic Release"

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tiwariav/github-actions/setup-yarn@main
      - uses: tiwariav/github-actions/cache-js-linters@main
      - run: yarn eslint --cache --cache-strategy=content --quiet src
      - run: yarn stylelint --cache ./src/**/*.css
      - run: yarn prettier --cache --check src
      - run: yarn jscpd src
      - run: yarn build
      - uses: tiwariav/github-actions/semantic-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
